### ISSUE TITLE
-fheinous-gnu-extensions in lib/mpi/longlong.h

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1898]
From a mips randconfig build of 4.19.y (but it looks like the issue probably still exists in mainline):
https://lore.kernel.org/llvm/202307311111.jPEdYIJR-lkp@intel.com/
```
>> lib/mpi/generic_mpih-mul2.c:49:24: error: invalid use of a cast in a inline asm context requiring an lvalue: remove the cast or build with -fheinous-gnu-extensions
      49 |                 umul_ppmm(prod_high, prod_low, s1_ptr[j], s2_limb);
         |                 ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   lib/mpi/longlong.h:652:20: note: expanded from macro 'umul_ppmm'
     652 |         : "=l" ((USItype)(w0)), \
         |                 ~~~~~~~~~~^~~
>> lib/mpi/generic_mpih-mul2.c:49:3: error: invalid output constraint '=h' in asm
      49 |                 umul_ppmm(prod_high, prod_low, s1_ptr[j], s2_limb);
         |                 ^
   lib/mpi/longlong.h:653:7: note: expanded from macro 'umul_ppmm'
     653 |              "=h" ((USItype)(w1)) \
         |              ^
   2 errors generated.
--
   lib/mpi/generic_mpih-mul3.c:49:24: error: invalid use of a cast in a inline asm context requiring an lvalue: remove the cast or build with -fheinous-gnu-extensions
      49 |                 umul_ppmm(prod_high, prod_low, s1_ptr[j], s2_limb);
         |                 ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   lib/mpi/longlong.h:652:20: note: expanded from macro 'umul_ppmm'
     652 |         : "=l" ((USItype)(w0)), \
         |                 ~~~~~~~~~~^~~
>> lib/mpi/generic_mpih-mul3.c:49:3: error: invalid output constraint '=h' in asm
      49 |                 umul_ppmm(prod_high, prod_low, s1_ptr[j], s2_limb);
         |                 ^
   lib/mpi/longlong.h:653:7: note: expanded from macro 'umul_ppmm'
     653 |              "=h" ((USItype)(w1)) \
         |              ^
   2 errors generated.
--
>> lib/mpi/mpih-div.c:142:20: error: invalid use of a cast in a inline asm context requiring an lvalue: remove the cast or build with -fheinous-gnu-extensions
     142 |                                         umul_ppmm(n1, n0, d0, q);
         |                                         ~~~~~~~~~~~~~~^~~~~~~~~~
   lib/mpi/longlong.h:652:20: note: expanded from macro 'umul_ppmm'
     652 |         : "=l" ((USItype)(w0)), \
         |                 ~~~~~~~~~~^~~
>> lib/mpi/mpih-div.c:142:6: error: invalid output constraint '=h' in asm
     142 |                                         umul_ppmm(n1, n0, d0, q);
         |                                         ^
   lib/mpi/longlong.h:653:7: note: expanded from macro 'umul_ppmm'
     653 |              "=h" ((USItype)(w1)) \
         |              ^
   lib/mpi/mpih-div.c:205:20: error: invalid use of a cast in a inline asm context requiring an lvalue: remove the cast or build with -fheinous-gnu-extensions
     205 |                                         umul_ppmm(n1, n0, d1, q);
         |                                         ~~~~~~~~~~~~~~^~~~~~~~~~
   lib/mpi/longlong.h:652:20: note: expanded from macro 'umul_ppmm'
     652 |         : "=l" ((USItype)(w0)), \
         |                 ~~~~~~~~~~^~~
   lib/mpi/mpih-div.c:205:6: error: invalid output constraint '=h' in asm
     205 |                                         umul_ppmm(n1, n0, d1, q);
         |                                         ^
   lib/mpi/longlong.h:653:7: note: expanded from macro 'umul_ppmm'
     653 |              "=h" ((USItype)(w1)) \
         |              ^
   4 errors generated.
--
>> lib/mpi/generic_mpih-mul1.c:50:24: error: invalid use of a cast in a inline asm context requiring an lvalue: remove the cast or build with -fheinous-gnu-extensions
      50 |                 umul_ppmm(prod_high, prod_low, s1_ptr[j], s2_limb);
         |                 ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   lib/mpi/longlong.h:652:20: note: expanded from macro 'umul_ppmm'
     652 |         : "=l" ((USItype)(w0)), \
         |                 ~~~~~~~~~~^~~
>> lib/mpi/generic_mpih-mul1.c:50:3: error: invalid output constraint '=h' in asm
      50 |                 umul_ppmm(prod_high, prod_low, s1_ptr[j], s2_limb);
         |                 ^
   lib/mpi/longlong.h:653:7: note: expanded from macro 'umul_ppmm'
     653 |              "=h" ((USItype)(w1)) \
         |              ^
```
The issue specifically seems to be the preprocessor define of `umul_ppmm` for `__mips` in lib/mpi/longlong.h.

These headers seem to be a downstream copy of GnuPG's multi-precision-integer (MPI) library.  I wonder if those have been updated to avoid this compiler error, such that the down stream kernel copies can be refreshed?

**Comment by nathanchance** [comment]
This is #605, fixed by https://git.kernel.org/linus/b0c091ae04f6746f541b9be91809e1f4f43e9a65. 4.19 was the first release that required 4.6 due to commit [cafa0010cd51](https://git.kernel.org/linus/cafa0010cd51fb711fdcb50fc55f394c5f167a0a) ("Raise the minimum required gcc version to 4.6"), so we can just take that patch wholesale. I'll reply upstream.

**Comment by nickdesaulniers** [comment]
> but it looks like the issue probably still exists in mainline):

ah, I was looking at the definitions for `MIPS/64` which appear to still have these casts (as do some other arch's).  Perhaps there are simply no macro expansion sites for these architectures in the kernel at the moment.

**Comment by nathanchance** [comment]
> ah, I was looking at the definitions for `MIPS/64` which appear to still have these casts (as do some other arch's).

Makes sense. I know that at least `MIPS/64` is fine because of https://git.kernel.org/linus/18f1ca46858eac22437819937ae44aa9a8f9f2fa.
