### ISSUE TITLE
Several new instances of -Wfortify-source after LLVM commit 0c9c9dd9a24f9

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1923]
After https://github.com/llvm/llvm-project/commit/0c9c9dd9a24f9d715d950fef0ac7aae01437af96, I see several new instances of `-Wfortify-source` (LKFT [reported one](https://lore.kernel.org/CA+G9fYscGFiG1TVLyfETVu3NV5BAe8sCOXRGDnky-w31aB6yVQ@mail.gmail.com/) as well):

```
drivers/input/misc/ims-pcu.c:1802:2: warning: 'snprintf' will always be truncated; specified size is 10, but format string expands to at least 12 [-Wfortify-source]
drivers/input/misc/ims-pcu.c:1814:2: warning: 'snprintf' will always be truncated; specified size is 10, but format string expands to at least 12 [-Wfortify-source]
drivers/media/pci/cx18/cx18-mailbox.c:99:3: warning: 'snprintf' will always be truncated; specified size is 12, but format string expands to at least 14 [-Wfortify-source]
drivers/net/ethernet/freescale/enetc/enetc.c:2771:3: warning: 'snprintf' will always be truncated; specified size is 80, but format string expands to at least 110 [-Wfortify-source]
drivers/net/ethernet/mellanox/mlx5/core/esw/bridge.c:1853:4: warning: 'snprintf' will always be truncated; specified size is 80, but format string expands to at least 94 [-Wfortify-source]
drivers/net/ethernet/qlogic/qed/qed_main.c:1218:3: warning: 'snprintf' will always be truncated; specified size is 16, but format string expands to at least 18 [-Wfortify-source]
drivers/net/ethernet/sfc/tc.c:521:5: warning: 'snprintf' will always be truncated; specified size is 80, but format string expands to at least 107 [-Wfortify-source]
drivers/net/ethernet/sfc/tc.c:528:5: warning: 'snprintf' will always be truncated; specified size is 80, but format string expands to at least 106 [-Wfortify-source]
drivers/platform/surface/surface3_power.c:248:3: warning: 'snprintf' will always be truncated; specified size is 10, but format string expands to at least 12 [-Wfortify-source]
drivers/s390/block/dasd_eckd.c:1082:3: warning: 'snprintf' will always be truncated; specified size is 1, but format string expands to at least 11 [-Wfortify-source]
drivers/s390/block/dasd_eckd.c:1087:3: warning: 'snprintf' will always be truncated; specified size is 1, but format string expands to at least 10 [-Wfortify-source]
drivers/scsi/myrb.c:1906:10: warning: 'snprintf' will always be truncated; specified size is 32, but format string expands to at least 34 [-Wfortify-source]
drivers/scsi/myrs.c:1089:10: warning: 'snprintf' will always be truncated; specified size is 32, but format string expands to at least 34 [-Wfortify-source]
drivers/scsi/myrs.cdrivers/scsi/myrb.c:1906:10: warning: 'snprintf' will always be truncated; specified size is 32, but format string expands to at least 34 [-Wfortify-source]
drivers/video/fbdev/neofb.c:1959:3: warning: 'snprintf' will always be truncated; specified size is 16, but format string expands to at least 17 [-Wfortify-source]
drivers/video/fbdev/neofb.c:1963:3: warning: 'snprintf' will always be truncated; specified size is 16, but format string expands to at least 18 [-Wfortify-source]
drivers/video/fbdev/neofb.c:1967:3: warning: 'snprintf' will always be truncated; specified size is 16, but format string expands to at least 17 [-Wfortify-source]
drivers/video/fbdev/neofb.c:1971:3: warning: 'snprintf' will always be truncated; specified size is 16, but format string expands to at least 17 [-Wfortify-source]
drivers/video/fbdev/neofb.c:1978:3: warning: 'snprintf' will always be truncated; specified size is 16, but format string expands to at least 18 [-Wfortify-source]
drivers/video/fbdev/neofb.c:1985:3: warning: 'snprintf' will always be truncated; specified size is 16, but format string expands to at least 17 [-Wfortify-source]
drivers/video/fbdev/neofb.c:1992:3: warning: 'snprintf' will always be truncated; specified size is 16, but format string expands to at least 18 [-Wfortify-source]
drivers/video/fbdev/sh_mobile_lcdcfb.c:1578:2: warning: 'snprintf' will always be truncated; specified size is 16, but format string expands to at least 25 [-Wfortify-source]
sound/aoa/soundbus/i2sbus/core.c:170:6: warning: 'snprintf' will always be truncated; specified size is 6, but format string expands to at least 7 [-Wfortify-source]
```

Not too many but for at least the `drivers/video/fbdev` ones, the size is in a UAPI header (`include/uapi/linux/fb.h`), so I am not really sure how we will go about fixing these...

I have not checked to see if GCC warns about these same instances but `-Wformat-truncation` is [disabled in mainline](https://elixir.bootlin.com/linux/v6.5/source/Makefile#L827) and [placed in `W=1` in -next](https://git.kernel.org/next/linux-next/c/6d4ab2e97dcfbcd748ae71761a9d8e5e41cc732c) but we don't get that same escape hatch because this is not a separate warning option.

**Comment by nathanchance** [comment]
GCC appears to flag most of these...

<details><summary>Full GCC warning instances</summary>

```
drivers/input/misc/ims-pcu.c: In function 'ims_pcu_get_device_info':
drivers/input/misc/ims-pcu.c:1803:31: error: '%02d' directive output may be truncated writing between 2 and 3 bytes into a region of size between 1 and 4 [-Werror=format-truncation=]
 1803 |                  "%02d%02d%02d%02d.%c%c",
      |                               ^~~~
drivers/input/misc/ims-pcu.c:1803:18: note: directive argument in the range [0, 255]
 1803 |                  "%02d%02d%02d%02d.%c%c",
      |                  ^~~~~~~~~~~~~~~~~~~~~~~
drivers/input/misc/ims-pcu.c:1802:9: note: 'snprintf' output between 12 and 16 bytes into a destination of size 10
 1802 |         snprintf(pcu->fw_version, sizeof(pcu->fw_version),
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1803 |                  "%02d%02d%02d%02d.%c%c",
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~
 1804 |                  pcu->cmd_buf[2], pcu->cmd_buf[3], pcu->cmd_buf[4], pcu->cmd_buf[5],
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1805 |                  pcu->cmd_buf[6], pcu->cmd_buf[7]);
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/input/misc/ims-pcu.c:1815:31: error: '%02d' directive output may be truncated writing between 2 and 3 bytes into a region of size between 1 and 4 [-Werror=format-truncation=]
 1815 |                  "%02d%02d%02d%02d.%c%c",
      |                               ^~~~
drivers/input/misc/ims-pcu.c:1815:18: note: directive argument in the range [0, 255]
 1815 |                  "%02d%02d%02d%02d.%c%c",
      |                  ^~~~~~~~~~~~~~~~~~~~~~~
drivers/input/misc/ims-pcu.c:1814:9: note: 'snprintf' output between 12 and 16 bytes into a destination of size 10
 1814 |         snprintf(pcu->bl_version, sizeof(pcu->bl_version),
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1815 |                  "%02d%02d%02d%02d.%c%c",
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~
 1816 |                  pcu->cmd_buf[2], pcu->cmd_buf[3], pcu->cmd_buf[4], pcu->cmd_buf[5],
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1817 |                  pcu->cmd_buf[6], pcu->cmd_buf[7]);
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

```
In file included from include/uapi/linux/neighbour.h:6,
                 from include/linux/netdevice.h:46,
                 from drivers/net/ethernet/freescale/enetc/enetc.h:6,
                 from drivers/net/ethernet/freescale/enetc/enetc.c:4:
In function 'enetc_setup_xdp_prog',
    inlined from 'enetc_setup_bpf' at drivers/net/ethernet/freescale/enetc/enetc.c:2791:10:
include/linux/netlink.h:115:13: error: ' TXQs for network stack (tot...' directive output truncated writing 31 bytes into a region of size between 0 and 14 [-Werror=format-truncation=]
  115 |         if (snprintf(__extack->_msg_buf, NETLINK_MAX_FMTMSG_LEN,               \
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  116 |                      "%s" fmt "%s", "", ##args, "") >=                         \
      |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
include/linux/netlink.h:130:9: note: in expansion of macro 'NL_SET_ERR_MSG_FMT'
  130 |         NL_SET_ERR_MSG_FMT((extack), KBUILD_MODNAME ": " fmt, ##args)
      |         ^~~~~~~~~~~~~~~~~~
drivers/net/ethernet/freescale/enetc/enetc.c:2771:17: note: in expansion of macro 'NL_SET_ERR_MSG_FMT_MOD'
 2771 |                 NL_SET_ERR_MSG_FMT_MOD(extack,
      |                 ^~~~~~~~~~~~~~~~~~~~~~
include/linux/netlink.h:115:13: note: directive argument in the range [0, 65535]
  115 |         if (snprintf(__extack->_msg_buf, NETLINK_MAX_FMTMSG_LEN,               \
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  116 |                      "%s" fmt "%s", "", ##args, "") >=                         \
      |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
include/linux/netlink.h:130:9: note: in expansion of macro 'NL_SET_ERR_MSG_FMT'
  130 |         NL_SET_ERR_MSG_FMT((extack), KBUILD_MODNAME ": " fmt, ##args)
      |         ^~~~~~~~~~~~~~~~~~
drivers/net/ethernet/freescale/enetc/enetc.c:2771:17: note: in expansion of macro 'NL_SET_ERR_MSG_FMT_MOD'
 2771 |                 NL_SET_ERR_MSG_FMT_MOD(extack,
      |                 ^~~~~~~~~~~~~~~~~~~~~~
include/linux/netlink.h:115:13: note: 'snprintf' output between 110 and 134 bytes into a destination of size 80
  115 |         if (snprintf(__extack->_msg_buf, NETLINK_MAX_FMTMSG_LEN,               \
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  116 |                      "%s" fmt "%s", "", ##args, "") >=                         \
      |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
include/linux/netlink.h:130:9: note: in expansion of macro 'NL_SET_ERR_MSG_FMT'
  130 |         NL_SET_ERR_MSG_FMT((extack), KBUILD_MODNAME ": " fmt, ##args)
      |         ^~~~~~~~~~~~~~~~~~
drivers/net/ethernet/freescale/enetc/enetc.c:2771:17: note: in expansion of macro 'NL_SET_ERR_MSG_FMT_MOD'
 2771 |                 NL_SET_ERR_MSG_FMT_MOD(extack,
      |                 ^~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

```
drivers/net/ethernet/qlogic/qed/qed_main.c: In function 'qed_slowpath_start':
drivers/net/ethernet/qlogic/qed/qed_main.c:1218:63: error: '%02x' directive output truncated writing 2 bytes into a region of size 1 [-Werror=format-truncation=]
 1218 |                 snprintf(name, NAME_SIZE, "slowpath-%02x:%02x.%02x",
      |                                                               ^~~~
In function 'qed_slowpath_wq_start',
    inlined from 'qed_slowpath_start' at drivers/net/ethernet/qlogic/qed/qed_main.c:1250:6:
drivers/net/ethernet/qlogic/qed/qed_main.c:1218:43: note: directive argument in the range [0, 255]
 1218 |                 snprintf(name, NAME_SIZE, "slowpath-%02x:%02x.%02x",
      |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~
drivers/net/ethernet/qlogic/qed/qed_main.c:1218:17: note: 'snprintf' output 18 bytes into a destination of size 16
 1218 |                 snprintf(name, NAME_SIZE, "slowpath-%02x:%02x.%02x",
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1219 |                          cdev->pdev->bus->number,
      |                          ~~~~~~~~~~~~~~~~~~~~~~~~
 1220 |                          PCI_SLOT(cdev->pdev->devfn), hwfn->abs_pf_id);
      |                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

```
In file included from include/uapi/linux/neighbour.h:6,
                 from include/linux/netdevice.h:46,
                 from include/net/sch_generic.h:5,
                 from include/net/pkt_cls.h:7,
                 from drivers/net/ethernet/sfc/tc.c:12:
drivers/net/ethernet/sfc/tc.c: In function 'efx_tc_flower_record_encap_match':
include/linux/netlink.h:115:13: error: ' conflicts with existing pse...' directive output truncated writing 53 bytes into a region of size between 28 and 33 [-Werror=format-truncation=]
  115 |         if (snprintf(__extack->_msg_buf, NETLINK_MAX_FMTMSG_LEN,               \
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  116 |                      "%s" fmt "%s", "", ##args, "") >=                         \
      |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
include/linux/netlink.h:130:9: note: in expansion of macro 'NL_SET_ERR_MSG_FMT'
  130 |         NL_SET_ERR_MSG_FMT((extack), KBUILD_MODNAME ": " fmt, ##args)
      |         ^~~~~~~~~~~~~~~~~~
drivers/net/ethernet/sfc/tc.c:528:33: note: in expansion of macro 'NL_SET_ERR_MSG_FMT_MOD'
  528 |                                 NL_SET_ERR_MSG_FMT_MOD(extack,
      |                                 ^~~~~~~~~~~~~~~~~~~~~~
include/linux/netlink.h:115:13: note: directive argument in the range [0, 65535]
  115 |         if (snprintf(__extack->_msg_buf, NETLINK_MAX_FMTMSG_LEN,               \
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  116 |                      "%s" fmt "%s", "", ##args, "") >=                         \
      |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
include/linux/netlink.h:130:9: note: in expansion of macro 'NL_SET_ERR_MSG_FMT'
  130 |         NL_SET_ERR_MSG_FMT((extack), KBUILD_MODNAME ": " fmt, ##args)
      |         ^~~~~~~~~~~~~~~~~~
drivers/net/ethernet/sfc/tc.c:528:33: note: in expansion of macro 'NL_SET_ERR_MSG_FMT_MOD'
  528 |                                 NL_SET_ERR_MSG_FMT_MOD(extack,
      |                                 ^~~~~~~~~~~~~~~~~~~~~~
include/linux/netlink.h:115:13: note: 'snprintf' output between 102 and 112 bytes into a destination of size 80
  115 |         if (snprintf(__extack->_msg_buf, NETLINK_MAX_FMTMSG_LEN,               \
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  116 |                      "%s" fmt "%s", "", ##args, "") >=                         \
      |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
include/linux/netlink.h:130:9: note: in expansion of macro 'NL_SET_ERR_MSG_FMT'
  130 |         NL_SET_ERR_MSG_FMT((extack), KBUILD_MODNAME ": " fmt, ##args)
      |         ^~~~~~~~~~~~~~~~~~
drivers/net/ethernet/sfc/tc.c:528:33: note: in expansion of macro 'NL_SET_ERR_MSG_FMT_MOD'
  528 |                                 NL_SET_ERR_MSG_FMT_MOD(extack,
      |                                 ^~~~~~~~~~~~~~~~~~~~~~
include/linux/netlink.h:115:13: error: ' conflicts with existing pse...' directive output truncated writing 57 bytes into a region of size 39 [-Werror=format-truncation=]
  115 |         if (snprintf(__extack->_msg_buf, NETLINK_MAX_FMTMSG_LEN,               \
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  116 |                      "%s" fmt "%s", "", ##args, "") >=                         \
      |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
include/linux/netlink.h:130:9: note: in expansion of macro 'NL_SET_ERR_MSG_FMT'
  130 |         NL_SET_ERR_MSG_FMT((extack), KBUILD_MODNAME ": " fmt, ##args)
      |         ^~~~~~~~~~~~~~~~~~
drivers/net/ethernet/sfc/tc.c:521:33: note: in expansion of macro 'NL_SET_ERR_MSG_FMT_MOD'
  521 |                                 NL_SET_ERR_MSG_FMT_MOD(extack,
      |                                 ^~~~~~~~~~~~~~~~~~~~~~
include/linux/netlink.h:115:13: note: directive argument in the range [0, 255]
  115 |         if (snprintf(__extack->_msg_buf, NETLINK_MAX_FMTMSG_LEN,               \
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  116 |                      "%s" fmt "%s", "", ##args, "") >=                         \
      |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
include/linux/netlink.h:130:9: note: in expansion of macro 'NL_SET_ERR_MSG_FMT'
  130 |         NL_SET_ERR_MSG_FMT((extack), KBUILD_MODNAME ": " fmt, ##args)
      |         ^~~~~~~~~~~~~~~~~~
drivers/net/ethernet/sfc/tc.c:521:33: note: in expansion of macro 'NL_SET_ERR_MSG_FMT_MOD'
  521 |                                 NL_SET_ERR_MSG_FMT_MOD(extack,
      |                                 ^~~~~~~~~~~~~~~~~~~~~~
include/linux/netlink.h:115:13: note: 'snprintf' output 103 bytes into a destination of size 80
  115 |         if (snprintf(__extack->_msg_buf, NETLINK_MAX_FMTMSG_LEN,               \
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  116 |                      "%s" fmt "%s", "", ##args, "") >=                         \
      |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
include/linux/netlink.h:130:9: note: in expansion of macro 'NL_SET_ERR_MSG_FMT'
  130 |         NL_SET_ERR_MSG_FMT((extack), KBUILD_MODNAME ": " fmt, ##args)
      |         ^~~~~~~~~~~~~~~~~~
drivers/net/ethernet/sfc/tc.c:521:33: note: in expansion of macro 'NL_SET_ERR_MSG_FMT_MOD'
  521 |                                 NL_SET_ERR_MSG_FMT_MOD(extack,
      |                                 ^~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

```
drivers/s390/block/dasd_eckd.c: In function 'dasd_eckd_get_uid_string':
drivers/s390/block/dasd_eckd.c:1088:27: error: '%s' directive output may be truncated writing up to 3 bytes into a region of size 1 [-Werror=format-truncation=]
 1088 |                          "%s.%s.%04x.%02x",
      |                           ^~
 1089 |                          uid.vendor, uid.serial, uid.ssid,
      |                          ~~~~~~~~~~
drivers/s390/block/dasd_eckd.c:1088:26: note: directive argument in the range [0, 65535]
 1088 |                          "%s.%s.%04x.%02x",
      |                          ^~~~~~~~~~~~~~~~~
drivers/s390/block/dasd_eckd.c:1088:26: note: directive argument in the range [0, 255]
drivers/s390/block/dasd_eckd.c:1087:17: note: 'snprintf' output between 10 and 27 bytes into a destination of size 1
 1087 |                 snprintf(print_uid, sizeof(*print_uid),
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1088 |                          "%s.%s.%04x.%02x",
      |                          ~~~~~~~~~~~~~~~~~~
 1089 |                          uid.vendor, uid.serial, uid.ssid,
      |                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1090 |                          uid.real_unit_addr);
      |                          ~~~~~~~~~~~~~~~~~~~
drivers/s390/block/dasd_eckd.c:1083:27: error: '%s' directive output may be truncated writing up to 3 bytes into a region of size 1 [-Werror=format-truncation=]
 1083 |                          "%s.%s.%04x.%02x.%s",
      |                           ^~
 1084 |                          uid.vendor, uid.serial, uid.ssid,
      |                          ~~~~~~~~~~
drivers/s390/block/dasd_eckd.c:1083:26: note: directive argument in the range [0, 65535]
 1083 |                          "%s.%s.%04x.%02x.%s",
      |                          ^~~~~~~~~~~~~~~~~~~~
drivers/s390/block/dasd_eckd.c:1083:26: note: directive argument in the range [0, 255]
drivers/s390/block/dasd_eckd.c:1082:17: note: 'snprintf' output between 11 and 60 bytes into a destination of size 1
 1082 |                 snprintf(print_uid, sizeof(*print_uid),
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1083 |                          "%s.%s.%04x.%02x.%s",
      |                          ~~~~~~~~~~~~~~~~~~~~~
 1084 |                          uid.vendor, uid.serial, uid.ssid,
      |                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1085 |                          uid.real_unit_addr, uid.vduit);
      |                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

```
drivers/scsi/myrb.c: In function 'rebuild_show':
drivers/scsi/myrb.c:1906:24: error: 'physical device - not rebuil...' directive output truncated writing 33 bytes into a region of size 32 [-Werror=format-truncation=]
 1906 |                 return snprintf(buf, 32, "physical device - not rebuilding\n");
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/scsi/myrb.c:1906:24: note: 'snprintf' output 34 bytes into a destination of size 32
drivers/scsi/myrb.c: In function 'myrb_get_hba_config':
drivers/scsi/myrb.c:1051:29: error: '%02u' directive output may be truncated writing between 2 and 3 bytes into a region of size between 2 and 5 [-Werror=format-truncation=]
 1051 |                 "%u.%02u-%c-%02u",
      |                             ^~~~
drivers/scsi/myrb.c:1051:17: note: directive argument in the range [0, 255]
 1051 |                 "%u.%02u-%c-%02u",
      |                 ^~~~~~~~~~~~~~~~~
drivers/scsi/myrb.c:1050:9: note: 'snprintf' output between 10 and 14 bytes into a destination of size 12
 1050 |         snprintf(cb->fw_version, sizeof(cb->fw_version),
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1051 |                 "%u.%02u-%c-%02u",
      |                 ~~~~~~~~~~~~~~~~~~
 1052 |                 enquiry2->fw.major_version,
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1053 |                 enquiry2->fw.minor_version,
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1054 |                 enquiry2->fw.firmware_type,
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1055 |                 enquiry2->fw.turn_id);
      |                 ~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

```
drivers/scsi/myrs.c: In function 'rebuild_show':
drivers/scsi/myrs.c:1089:24: error: 'physical device - not rebuil...' directive output truncated writing 33 bytes into a region of size 32 [-Werror=format-truncation=]
 1089 |                 return snprintf(buf, 32, "physical device - not rebuilding\n");
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/scsi/myrs.c:1089:24: note: 'snprintf' output 34 bytes into a destination of size 32
cc1: all warnings being treated as errors
```

```
drivers/video/fbdev/neofb.c: In function 'neo_alloc_fb_info':
drivers/video/fbdev/neofb.c:1968:50: error: 'snprintf' output truncated before the last format character [-Werror=format-truncation=]
 1968 |                                 "MagicGraph 128XD");
      |                                                  ^
drivers/video/fbdev/neofb.c:1967:17: note: 'snprintf' output 17 bytes into a destination of size 16
 1967 |                 snprintf(info->fix.id, sizeof(info->fix.id),
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1968 |                                 "MagicGraph 128XD");
      |                                 ~~~~~~~~~~~~~~~~~~~
drivers/video/fbdev/neofb.c:1986:50: error: 'snprintf' output truncated before the last format character [-Werror=format-truncation=]
 1986 |                                 "MagicGraph 256ZX");
      |                                                  ^
drivers/video/fbdev/neofb.c:1985:17: note: 'snprintf' output 17 bytes into a destination of size 16
 1985 |                 snprintf(info->fix.id, sizeof(info->fix.id),
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1986 |                                 "MagicGraph 256ZX");
      |                                 ~~~~~~~~~~~~~~~~~~~
drivers/video/fbdev/neofb.c:1993:50: error: 'MagicGraph 256XL+' directive output truncated writing 17 bytes into a region of size 16 [-Werror=format-truncation=]
 1993 |                                 "MagicGraph 256XL+");
      |                                  ~~~~~~~~~~~~~~~~^
drivers/video/fbdev/neofb.c:1992:17: note: 'snprintf' output 18 bytes into a destination of size 16
 1992 |                 snprintf(info->fix.id, sizeof(info->fix.id),
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1993 |                                 "MagicGraph 256XL+");
      |                                 ~~~~~~~~~~~~~~~~~~~~
drivers/video/fbdev/neofb.c:1972:50: error: 'snprintf' output truncated before the last format character [-Werror=format-truncation=]
 1972 |                                 "MagicGraph 256AV");
      |                                                  ^
drivers/video/fbdev/neofb.c:1971:17: note: 'snprintf' output 17 bytes into a destination of size 16
 1971 |                 snprintf(info->fix.id, sizeof(info->fix.id),
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1972 |                                 "MagicGraph 256AV");
      |                                 ~~~~~~~~~~~~~~~~~~~
drivers/video/fbdev/neofb.c:1979:50: error: 'MagicGraph 256AV+' directive output truncated writing 17 bytes into a region of size 16 [-Werror=format-truncation=]
 1979 |                                 "MagicGraph 256AV+");
      |                                  ~~~~~~~~~~~~~~~~^
drivers/video/fbdev/neofb.c:1978:17: note: 'snprintf' output 18 bytes into a destination of size 16
 1978 |                 snprintf(info->fix.id, sizeof(info->fix.id),
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1979 |                                 "MagicGraph 256AV+");
      |                                 ~~~~~~~~~~~~~~~~~~~~
drivers/video/fbdev/neofb.c:1960:50: error: 'snprintf' output truncated before the last format character [-Werror=format-truncation=]
 1960 |                                 "MagicGraph 128ZV");
      |                                                  ^
drivers/video/fbdev/neofb.c:1959:17: note: 'snprintf' output 17 bytes into a destination of size 16
 1959 |                 snprintf(info->fix.id, sizeof(info->fix.id),
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1960 |                                 "MagicGraph 128ZV");
      |                                 ~~~~~~~~~~~~~~~~~~~
drivers/video/fbdev/neofb.c:1964:50: error: 'MagicGraph 128ZV+' directive output truncated writing 17 bytes into a region of size 16 [-Werror=format-truncation=]
 1964 |                                 "MagicGraph 128ZV+");
      |                                  ~~~~~~~~~~~~~~~~^
drivers/video/fbdev/neofb.c:1963:17: note: 'snprintf' output 18 bytes into a destination of size 16
 1963 |                 snprintf(info->fix.id, sizeof(info->fix.id),
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1964 |                                 "MagicGraph 128ZV+");
      |                                 ~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

```
drivers/video/fbdev/sh_mobile_lcdcfb.c: In function 'sh_mobile_lcdc_overlay_fb_init':
drivers/video/fbdev/sh_mobile_lcdcfb.c:1579:35: error: 'SH Mobile LCDC Overlay ' directive output truncated writing 23 bytes into a region of size 16 [-Werror=format-truncation=]
 1579 |                  "SH Mobile LCDC Overlay %u", ovl->index);
      |                   ~~~~~~~~~~~~~~~~^~~~~~~
drivers/video/fbdev/sh_mobile_lcdcfb.c:1578:9: note: 'snprintf' output between 25 and 34 bytes into a destination of size 16
 1578 |         snprintf(info->fix.id, sizeof(info->fix.id),
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1579 |                  "SH Mobile LCDC Overlay %u", ovl->index);
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```
</details>

It does not show any warning for
- `drivers/media/pci/cx18/cx18-mailbox.c`
- `drivers/net/ethernet/mellanox/mlx5/core/esw/bridge.c`
- `drivers/platform/surface/surface3_power.c`
- `sound/aoa/soundbus/i2sbus/core.c`

so it is possible that the `clang` warning needs further adjustment (it could be related to some of the kernel's special format specifiers?).

At the end of the day, these instances seem like they should be fixed but in my opinion, I think it is somewhat unfair that we have to do it because we see the warnings while GCC doesn't because it was implemented in `-Wfortify-source` and not `-Wformat-truncation`...

**Comment by nickdesaulniers** [comment]
> so it is possible that the clang warning needs further adjustment (it could be related to some of the kernel's special format specifiers?).

FWIW, the documentation for some of these is under Documentation/core-api/printk-formats.rst.
Also FWIW, a few of these seem to be stemming from the use of `NL_SET_ERR_MSG_FMT_MOD`.

---

Let's look at one case at a time, starting with sound/aoa/soundbus/i2sbus/core.c.

```c
if (snprintf(node_name, sizeof(node_name), "%pOFn", np) != 5)
```

so we have `%pOFn` which is a kernel specific format flag documented in Documentation/core-api/printk-formats.rst as device node name.  Because that's specific to the kernel, the compiler has no idea that `%pOFn` is one format flag. Instead, the compiler sees `%p` as the format flag, followed by 3 chars `OFn` then the NUL-terminator.  So to the unaware compiler, the destination has size 6B, and the `%p` flag would expand to something like `0x5572ba31b180` which is much larger than 6B.  In fact this test case:

```c
// clang -c -Wfortify-source tmp.c
char node_name [1];

void foo (void *n) {
    __builtin_snprintf(node_name, sizeof(node_name), "%p", n);
}
```
produces:
```
tmp.c:6:5: warning: 'snprintf' will always be truncated; specified size is 1, but format string expands to at least 4 [-Wfortify-source]
    6 |     __builtin_snprintf(node_name, sizeof(node_name), "%p", n);
      |     ^
1 warning generated.
```
so clang thinks that `%p` is "at least 4" which is true but somewhat misleading (for the implied `-m64` where `sizeof(void*) == 8` not 4); clang could tell us "but format string expands to 8" rather than "well maybe something larger than 4, idk you figure it out, LOL." Also, I don't think the warning accounts for the trailing NUL-byte (try `char node_name[5];`).

So then it thinks that `%pOFn` is 8 + 3 == 11B, which is larger than `char node_name [6]`.

Now I'm curious why GCC doesn't warn for this; is that intentional, or a bug?  Looking through some GCC commits, it doesn't seem intentional.

---

Finally FWIW, commit be58f7103700 ("fortify: Add compile-time FORTIFY_SOURCE tests") seems to have added `$(call cc-disable-warning,fortify-source)` in lib/Makefile.

**Comment by nickdesaulniers** [comment]
> Now I'm curious why GCC doesn't warn for this; is that intentional, or a bug? Looking through some GCC commits, it doesn't seem intentional.

Filed https://gcc.gnu.org/bugzilla/show_bug.cgi?id=111219 against GCC.

**Comment by nickdesaulniers** [comment]
> drivers/scsi/myrb.c:1906:10: warning: 'snprintf' will always be truncated; specified size is 32, but format string expands to at least 34 [-Wfortify-source]

in function `rebuild_show` which looks unused to me. Why does `-Wno-unused-function` not appear in any kbuild files... :monocle_face: 

EDIT: nevermind, is used:

 1153 | static DEVICE_ATTR_RW(rebuild);

**Comment by nickdesaulniers** [comment]
> > Now I'm curious why GCC doesn't warn for this; is that intentional, or a bug? Looking through some GCC commits, it doesn't seem intentional.
> 
> Filed https://gcc.gnu.org/bugzilla/show_bug.cgi?id=111219 against GCC.

Andrew pointed out %p omission is intentional: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=78512.

**Comment by nickdesaulniers** [comment]
> Not too many but for at least the drivers/video/fbdev ones, the size is in a UAPI header (include/uapi/linux/fb.h), so I am not really sure how we will go about fixing these...

commit 0e9045494aa5 ("neofb: avoid overwriting fb_info fields")
also alluded to the truncation, back in 2008 :sunglasses: 

Maybe a question for:
> Helge Deller <deller@gmx.de> (maintainer:FRAMEBUFFER LAYER)
> linux-fbdev@vger.kernel.org (open list:FRAMEBUFFER LAYER)
> dri-devel@lists.freedesktop.org (open list:FRAMEBUFFER LAYER)

**Comment by nickdesaulniers** [comment]
```
drivers/s390/block/dasd_eckd.c:1082:3: warning: 'snprintf' will always be truncated; specified size is 1, but format string expands to at least 11 [-Wfortify-source]
drivers/s390/block/dasd_eckd.c:1087:3: warning: 'snprintf' will always be truncated; specified size is 1, but format string expands to at least 10 [-Wfortify-source]
```
These 2 are very clearly bugs in the source.

**Comment by nathanchance** [comment]
> ```
> 
> drivers/s390/block/dasd_eckd.c:1082:3: warning: 'snprintf' will always be truncated; specified size is 1, but format string expands to at least 11 [-Wfortify-source]
> 
> drivers/s390/block/dasd_eckd.c:1087:3: warning: 'snprintf' will always be truncated; specified size is 1, but format string expands to at least 10 [-Wfortify-source]
> 
> ```
> 
> These 2 are very clearly bugs in the source.

I saw a fix for these fly by earlier today: https://lore.kernel.org/20230828153142.2843753-2-hca@linux.ibm.com/

Haven't tested it though.

**Comment by nickdesaulniers** [comment]
So for the non-`%p` cases, we can probably fix those in the kernel sources.
https://github.com/llvm/llvm-project/issues/64871#issuecomment-1696486537 is the upstream report that we may need to match this behavior in GCC, or split off a flag from -Wfortify-source in order to disable this checking.  We might want to check with @kees too about if the fortify implementation has issues with these custom format strings, too (or not).

**Comment by nickdesaulniers** [comment]
> > Not too many but for at least the drivers/video/fbdev ones, the size is in a UAPI header (include/uapi/linux/fb.h), so I am not really sure how we will go about fixing these...
> 
> commit [0e90454](https://github.com/ClangBuiltLinux/linux/commit/0e9045494aa50f34b774a7449dde4128240a7b00) ("neofb: avoid overwriting fb_info fields") also alluded to the truncation, back in 2008 😎
> 
> Maybe a question for:
> 
> > Helge Deller [deller@gmx.de](mailto:deller@gmx.de) (maintainer:FRAMEBUFFER LAYER)
> > [linux-fbdev@vger.kernel.org](mailto:linux-fbdev@vger.kernel.org) (open list:FRAMEBUFFER LAYER)
> > [dri-devel@lists.freedesktop.org](mailto:dri-devel@lists.freedesktop.org) (open list:FRAMEBUFFER LAYER)

Reported upstream: https://lore.kernel.org/llvm/CAKwvOdn0xoVWjQ6ufM_rojtKb0f1i1hW-J_xYGfKDNFdHwaeHQ@mail.gmail.com/

**Comment by hazohelet** [comment]
> It does not show any warning for
> 
> * `drivers/media/pci/cx18/cx18-mailbox.c`
> * `drivers/net/ethernet/mellanox/mlx5/core/esw/bridge.c`
> * `drivers/platform/surface/surface3_power.c`
> * `sound/aoa/soundbus/i2sbus/core.c`

FYI, I submitted https://reviews.llvm.org/D159138 to address the false positive in `drivers/media/pci/cx18/cx18-mailbox.c`

**Comment by nickdesaulniers** [comment]
> > > Not too many but for at least the drivers/video/fbdev ones, the size is in a UAPI header (include/uapi/linux/fb.h), so I am not really sure how we will go about fixing these...
> > 
> > 
> > commit [0e90454](https://github.com/ClangBuiltLinux/linux/commit/0e9045494aa50f34b774a7449dde4128240a7b00) ("neofb: avoid overwriting fb_info fields") also alluded to the truncation, back in 2008 😎
> > Maybe a question for:
> > > Helge Deller [deller@gmx.de](mailto:deller@gmx.de) (maintainer:FRAMEBUFFER LAYER)
> > > [linux-fbdev@vger.kernel.org](mailto:linux-fbdev@vger.kernel.org) (open list:FRAMEBUFFER LAYER)
> > > [dri-devel@lists.freedesktop.org](mailto:dri-devel@lists.freedesktop.org) (open list:FRAMEBUFFER LAYER)
> 
> Reported upstream: https://lore.kernel.org/llvm/CAKwvOdn0xoVWjQ6ufM_rojtKb0f1i1hW-J_xYGfKDNFdHwaeHQ@mail.gmail.com/

Helge is working on a patch in:
https://git.kernel.org/pub/scm/linux/kernel/git/deller/linux-fbdev.git/commit/?h=for-next&id=d98e0096dc040c6ea60dc842439be7372ee0b15b

Though I had some feedback:
https://lore.kernel.org/llvm/CAKwvOdkXmEe46cG9Hn837215ghWA7UNKtg7ZQM8CpQcEQnoWfg@mail.gmail.com/

**Comment by nickdesaulniers** [comment]
Until we have a way of disabling `%p` related issues (or clang ignores them like gcc), I think we should disable `-Wfortify-source` when using clang-18+ (or hide it behind W=2).

**Comment by nickdesaulniers** [comment]
@hazohelet has fixed the false-positive related to %#o, %#x, and %#X (drivers/media/pci/cx18/cx18-mailbox.c) and has a patch related to %n in https://github.com/llvm/llvm-project/pull/65969. Richard asked that this be split out into it's own flag so we can disable it (-Wno-fortify-source-percent-p or -Wno-fortify-source-gcc-compat or some such).

**Comment by nickdesaulniers** [comment]
@hazohelet has https://github.com/llvm/llvm-project/pull/65969 to split the warning into `-Wformat-truncation` and `-Wformat-truncation` AND address `%p`. I'm testing it now.

**Comment by nathanchance** [comment]
I think we will need to send something like this to ensure we never see warnings from `%p`:

```diff
diff --git a/scripts/Makefile.extrawarn b/scripts/Makefile.extrawarn
index 2fe6f2828d37..7fb1c4db41a9 100644
--- a/scripts/Makefile.extrawarn
+++ b/scripts/Makefile.extrawarn
@@ -106,6 +106,12 @@ KBUILD_CFLAGS += $(call cc-option, -Wunused-const-variable)
 KBUILD_CFLAGS += $(call cc-option, -Wpacked-not-aligned)
 KBUILD_CFLAGS += $(call cc-option, -Wformat-overflow)
 KBUILD_CFLAGS += $(call cc-option, -Wformat-truncation)
+# Clang checks for overflow/truncation with '%p', while GCC does not:
+# https://gcc.gnu.org/bugzilla/show_bug.cgi?id=111219
+# The kernel has many extensions to '%p' that clang does not understand, so
+# disable these warnings.
+KBUILD_CFLAGS += $(call cc-disable-warning, format-overflow-non-kprintf)
+KBUILD_CFLAGS += $(call cc-disable-warning, format-truncation-non-kprintf)
 KBUILD_CFLAGS += $(call cc-option, -Wstringop-overflow)
 KBUILD_CFLAGS += $(call cc-option, -Wstringop-truncation)
```

but the immediate issue of seeing these warnings is resolved with that PR (at least for me).

**Comment by nickdesaulniers** [comment]
> I think we will need to send something like this to ensure we never see warnings from %p:

That's what I was thinking as well, though with https://github.com/llvm/llvm-project/pull/65969 applied, I did not observe any instances on mainline of those two for ARCH=x86_64.  Did you observe any for other architectures?

Perhaps the TUs listed in https://github.com/ClangBuiltLinux/linux/issues/1923#issuecomment-1696075886 (and maybe for 32b architectures)?

**Comment by nathanchance** [comment]
> That's what I was thinking as well, though with [llvm/llvm-project#65969](https://github.com/llvm/llvm-project/pull/65969) applied, I did not observe any instances on mainline of those two for ARCH=x86_64. Did you observe any for other architectures?

You should not see any warnings currently due to `-Wno-format-truncation` in the default kernel build. `-Wformat-truncation` is now in `W=1`, which is where I was able to see the warning in `drivers/platform/surface/surface3_power.c` without that diff (and it disappears with it).

**Comment by nickdesaulniers** [comment]
Ah! Right, Arnd's recent changes to scripts/Makefile.extrawarn.

With x86_64 allyesconfig KCFLAGS="-Wformat-truncation -Wformat-overflow":

drivers/net/ethernet/mellanox/mlx5/core/esw/bridge.c:1853:4: error: 'snprintf' will always be truncated; specified size is 80, but format string expands to at least 94 [-Werror,-Wformat-truncation-non-kprintf]
drivers/platform/surface/surface3_power.c:248:3: error: 'snprintf' will always be truncated; specified size is 10, but format string expands to at least 12 [-Werror,-Wformat-truncation-non-kprintf]

and again with KCFLAGS="-Wformat-truncation -Wformat-overflow -Wno-format-truncation-non-kprintf", those two are gone.

So it looks like https://github.com/llvm/llvm-project/pull/65969 works pretty nicely; it can tell when `%p` is perhaps the culprit.

If we don't have any instances of `-Wformat-overflow`, perhaps then we don't yet need to disable `format-overflow-non-kprintf`? (referring to [your kernel diff above](https://github.com/ClangBuiltLinux/linux/issues/1923#issuecomment-1718144462))

**Comment by nathanchance** [comment]
> If we don't have any instances of `-Wformat-overflow`, perhaps then we don't yet need to disable `format-overflow-non-kprintf`? (referring to [your kernel diff above](https://github.com/ClangBuiltLinux/linux/issues/1923#issuecomment-1718144462))

Maybe not but won't instances of `-Wformat-overflow-non-kprintf` be potential false positives for the same reason?

**Comment by nickdesaulniers** [comment]
Yes though -Wformat-overflow is pretty rare.

**Comment by nathanchance** [comment]
I'll send whatever diff you are willing to sign off on :) we can either turn off both now or we can turn off truncation now and overflow when it matters, I don't personally have much of a preference.

I'll wait to send the change until the LLVM PR lands and we are pretty confident it won't get reverted, just to make sure we don't have dead code in the kernel.

**Comment by nickdesaulniers** [comment]
I suspect clang-18 is now fixed (but haven't yet confirmed the logs)

**Comment by nickdesaulniers** [comment]
Even with https://github.com/llvm/llvm-project/commit/56c3b8e997d065b568964f71715ecbbd28c2e4a4, we still have numerous instances of `-Wfortify-source` due to actual kernel bugs in drivers that need structural reworking, so we will likely need https://github.com/ClangBuiltLinux/linux/issues/1923#issuecomment-1718144462 (untested).

@nathanchance next week can you test + send https://github.com/ClangBuiltLinux/linux/issues/1923#issuecomment-1718144462 ?

**Comment by nathanchance** [comment]
Yes, I'll add it to my TODO but if we are still seeing warnings even with that LLVM change merged, something has gone wrong with that change. We shouldn't be seeing these instances due to `-Wno-format-truncation`.

**Comment by nathanchance** [comment]
It looks like CI has picked up https://github.com/llvm/llvm-project/commit/56c3b8e997d065b568964f71715ecbbd28c2e4a4, as mainline clang-18 is now green: https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/6380048759

**Comment by nathanchance** [comment]
Diff properly submitted: https://lore.kernel.org/20231002-disable-wformat-truncation-overflow-non-kprintf-v1-1-35179205c8d9@kernel.org/

**Comment by nathanchance** [comment]
This should be all squared away as of commit [908dd508276d](https://git.kernel.org/linus/908dd508276da13a9b50c208577365d26692eb43) ("kbuild: enable -Wformat-truncation on clang") in 6.10.
