### ISSUE TITLE
x86_64 boot regression after rL354053

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#368]
While the kernel builds after #367 was resolved, it does not boot in QEMU. I know it is related to [rL354053](https://github.com/llvm/llvm-project/commit/90868bb0584f657c2b307309c217dece1f13b0ac) as [rL354052](https://github.com/llvm/llvm-project/commit/980fb790c1791cbf7589053b15fccb6f9c14db5d) works fine and as soon as I move to rL354053 (plus the two follow up fixes, [rL354163](https://github.com/llvm/llvm-project/commit/78758411217cb21c420d40a0b4affdb71f979663) and [rL354211](https://github.com/llvm/llvm-project/commit/91ecb69acdf4cffb4f879e12716465169848633e), the kernel no longer boots.

Unfortunately, there is no console output with [our QEMU flags](https://github.com/ClangBuiltLinux/continuous-integration/blob/7d55d76d3a09cb82b6ca7ef7435943d6cacb4e71/driver.sh#L92-L93) from CI so this will require further triage, which I'll be free to do tomorrow as I have a day off. Just wanted to file this as soon as I was aware.

**Comment by nickdesaulniers** [comment]
cc @niravhdave .  I wonder if grepping for `@cc` or `__GCC_ASM_FLAG_OUTPUTS__` turns up any hits in the kernel, otherwise @niravhdave 's changes seem pretty innocuous.

**Comment by niravhdave** [comment]
I wonder if the kernel is missing a clobber of the flags output for a use.
I've been assuming we need to explicitlh add it in the inline ASM clobbers.

**Comment by nathanchance** [comment]
When grepping for `__GCC_ASM_FLAG_OUTPUTS__`, two places show up:

https://github.com/ClangBuiltLinux/linux/blob/a3b22b9f11d9fbc48b0291ea92259a5a810e9438/arch/x86/include/asm/asm.h#L108-L118

https://github.com/ClangBuiltLinux/linux/blob/a3b22b9f11d9fbc48b0291ea92259a5a810e9438/arch/x86/include/asm/rmwcc.h#L14-L41

However, the latter doesn't matter because `CONFIG_CC_HAS_ASM_GOTO` has never been defined with Clang.

Not much to go on, especially since I have attempted to debug via gdb and it is hanging so early that I can't print out dmesg...

**Comment by nickdesaulniers** [comment]
Try modifying those source files to never handle the true case (when `__GCC_ASM_FLAG_OUTPUTS__` is defined), since that's what @niravhdave  added in [rL354053](https://github.com/llvm/llvm-project/commit/90868bb0584f657c2b307309c217dece1f13b0ac) .  The first case looks highly related; so I assume we can fine one call site that's broken (assuming the false case has no issues, if that makes sense).

**Comment by nathanchance** [comment]
So yes, the false case has no issues:

```diff

diff --git a/arch/x86/include/asm/asm.h b/arch/x86/include/asm/asm.h
index 6467757bb39f..66be7b17c6ab 100644
--- a/arch/x86/include/asm/asm.h
+++ b/arch/x86/include/asm/asm.h
@@ -109,13 +109,8 @@
  * Macros to generate condition code outputs from inline assembly,
  * The output operand must be type "bool".
  */
-#ifdef __GCC_ASM_FLAG_OUTPUTS__
-# define CC_SET(c) "\n\t/* output condition code " #c "*/\n"
-# define CC_OUT(c) "=@cc" #c
-#else
 # define CC_SET(c) "\n\tset" #c " %[_cc_" #c "]\n"
 # define CC_OUT(c) [_cc_ ## c] "=qm"
-#endif

 /* Exception table entry */
 #ifdef __ASSEMBLY__
```

I've spent the entire evening trying to hunt down a specific section of the kernel where the current true part causes an issue but I can't get anything conclusive right now. I'll keep trying tomorrow.

**Comment by nickdesaulniers** [comment]
Cool, we're on the right track.  Next, let's figure out if it's one, the other, or both.  Try seeing if having "the false case" for just one or the other is enough to reproduce the issue.  CC_SET and CC_OUT have 28 macro expansion sites by my count (times 2 macros, so 56 potentially problematic sites).  Hopefully we can cut that in half.  Then, we may be able to narrow down the problematic site by keeping the "false" case, but at individual sites replacing them with the the "true" case one by one to see which is problematic (assuming it's one site, and not ALL sites).

**Comment by nathanchance** [comment]
```diff
diff --git a/arch/x86/include/asm/asm.h b/arch/x86/include/asm/asm.h
index 6467757bb39f..5e4602a25ea3 100644
--- a/arch/x86/include/asm/asm.h
+++ b/arch/x86/include/asm/asm.h
@@ -111,9 +111,6 @@
  */
 #ifdef __GCC_ASM_FLAG_OUTPUTS__
 # define CC_SET(c) "\n\t/* output condition code " #c "*/\n"
-# define CC_OUT(c) "=@cc" #c
-#else
-# define CC_SET(c) "\n\tset" #c " %[_cc_" #c "]\n"
 # define CC_OUT(c) [_cc_ ## c] "=qm"
 #endif
```

has the issue.

```diff
diff --git a/arch/x86/include/asm/asm.h b/arch/x86/include/asm/asm.h
index 6467757bb39f..04bf586df492 100644
--- a/arch/x86/include/asm/asm.h
+++ b/arch/x86/include/asm/asm.h
@@ -110,11 +110,8 @@
  * The output operand must be type "bool".
  */
 #ifdef __GCC_ASM_FLAG_OUTPUTS__
-# define CC_SET(c) "\n\t/* output condition code " #c "*/\n"
-# define CC_OUT(c) "=@cc" #c
-#else
 # define CC_SET(c) "\n\tset" #c " %[_cc_" #c "]\n"
-# define CC_OUT(c) [_cc_ ## c] "=qm"
+# define CC_OUT(c) "=@cc" #c
 #endif

 /* Exception table entry */
```

doesn't build.

```
/home/nathan/cbl/linux-next/arch/x86/include/asm/bitops.h:214:9: error: unknown symbolic operand name in inline assembly string
        return GEN_BINARY_RMWcc(LOCK_PREFIX __ASM_SIZE(bts), *addr, c, "Ir", nr);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/nathan/cbl/linux-next/arch/x86/include/asm/rmwcc.h:60:32: note: expanded from macro 'GEN_BINARY_RMWcc'
#define GEN_BINARY_RMWcc(X...) RMWcc_CONCAT(GEN_BINARY_RMWcc_, RMWcc_ARGS(X))(X)
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/nathan/cbl/linux-next/arch/x86/include/asm/rmwcc.h:10:28: note: expanded from macro 'RMWcc_CONCAT'
#define RMWcc_CONCAT(a, b) __RMWcc_CONCAT(a, b)
                           ^
/home/nathan/cbl/linux-next/arch/x86/include/asm/rmwcc.h:9:30: note: expanded from macro '__RMWcc_CONCAT'
#define __RMWcc_CONCAT(a, b) a ## b
                             ^
note: (skipping 2 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/home/nathan/cbl/linux-next/arch/x86/include/asm/rmwcc.h:54:2: note: expanded from macro 'GEN_BINARY_RMWcc_6'
        __GEN_RMWcc(op " %[val], " arg0, var, cc,                       \
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/nathan/cbl/linux-next/arch/x86/include/asm/rmwcc.h:37:23: note: expanded from macro '__GEN_RMWcc'
        asm volatile (fullop CC_SET(cc)                                 \
                      ~~~~~~~^~~~~~~~~~
/home/nathan/cbl/linux-next/arch/x86/include/asm/asm.h:113:37: note: expanded from macro 'CC_SET'
# define CC_SET(c) "\n\tset" #c " %[_cc_" #c "]\n"
                                    ^
```

I'm going to try narrowing down the call sites again, as I tried what you suggested last night. This diff is what I came up with last night to cause the issue:

```diff
diff --git a/arch/x86/include/asm/asm.h b/arch/x86/include/asm/asm.h
index 6467757bb39f..66be7b17c6ab 100644
--- a/arch/x86/include/asm/asm.h
+++ b/arch/x86/include/asm/asm.h
@@ -109,13 +109,8 @@
  * Macros to generate condition code outputs from inline assembly,
  * The output operand must be type "bool".
  */
-#ifdef __GCC_ASM_FLAG_OUTPUTS__
-# define CC_SET(c) "\n\t/* output condition code " #c "*/\n"
-# define CC_OUT(c) "=@cc" #c
-#else
 # define CC_SET(c) "\n\tset" #c " %[_cc_" #c "]\n"
 # define CC_OUT(c) [_cc_ ## c] "=qm"
-#endif
  
 /* Exception table entry */
 #ifdef __ASSEMBLY__
diff --git a/arch/x86/include/asm/bitops.h b/arch/x86/include/asm/bitops.h
index d153d570bb04..5da87c509ba2 100644
--- a/arch/x86/include/asm/bitops.h
+++ b/arch/x86/include/asm/bitops.h
@@ -18,6 +18,11 @@
 #include <asm/rmwcc.h>
 #include <asm/barrier.h>
  
+#undef CC_SET
+#define CC_SET(c) "\n\t/* output condition code " #c "*/\n"
+#undef CC_OUT
+#define CC_OUT(c) "=@cc" #c
+ 
 #if BITS_PER_LONG == 32
 # define _BITOPS_LONG_SHIFT 5
 #elif BITS_PER_LONG == 64
```

I'm sure it can be narrowed down further though and I am going to double check my results.

**Comment by nathanchance** [comment]
Sweet victory!

```diff
diff --git a/arch/x86/include/asm/asm.h b/arch/x86/include/asm/asm.h
index 6467757bb39f..44af02a92c2c 100644
--- a/arch/x86/include/asm/asm.h
+++ b/arch/x86/include/asm/asm.h
@@ -109,13 +109,11 @@
  * Macros to generate condition code outputs from inline assembly,
  * The output operand must be type "bool".
  */
-#ifdef __GCC_ASM_FLAG_OUTPUTS__
 # define CC_SET(c) "\n\t/* output condition code " #c "*/\n"
 # define CC_OUT(c) "=@cc" #c
-#else
-# define CC_SET(c) "\n\tset" #c " %[_cc_" #c "]\n"
-# define CC_OUT(c) [_cc_ ## c] "=qm"
-#endif
+
+# define __CC_SET(c) "\n\tset" #c " %[_cc_" #c "]\n"
+# define __CC_OUT(c) [_cc_ ## c] "=qm"
 
 /* Exception table entry */
 #ifdef __ASSEMBLY__
diff --git a/arch/x86/include/asm/cmpxchg.h b/arch/x86/include/asm/cmpxchg.h
index a8bfac131256..fe96537622a2 100644
--- a/arch/x86/include/asm/cmpxchg.h
+++ b/arch/x86/include/asm/cmpxchg.h
@@ -190,8 +190,8 @@ extern void __add_wrong_size(void)
 	{								\
 		volatile u32 *__ptr = (volatile u32 *)(_ptr);		\
 		asm volatile(lock "cmpxchgl %[new], %[ptr]"		\
-			     CC_SET(z)					\
-			     : CC_OUT(z) (success),			\
+			     __CC_SET(z)				\
+			     : __CC_OUT(z) (success),			\
 			       [ptr] "+m" (*__ptr),			\
 			       [old] "+a" (__old)			\
 			     : [new] "r" (__new)			\
```

This diff on top of b5372fe5dc84235dbe04998efdede3c4daa866a9 and our two CI patches boots so it looks like there is only one problematic call site: https://github.com/ClangBuiltLinux/linux/blob/a3b22b9f11d9fbc48b0291ea92259a5a810e9438/arch/x86/include/asm/cmpxchg.h#L189-L200

I'll see if I can narrow it down farther.

**Comment by nickdesaulniers** [comment]
So there's probably a call to `try_cmpxchg` somewhere the first arg is some kind of int* (something where `sizeof(*ptr) == 4`, but I wonder if the third arg is larger than u32?  I bet we could catch that real quick with a `_Static_assert(sizeof(__old) == sizeof(__new), "oh no");`.  Otherwise I'd be curious how many macro expansion sites there are of `try_cmpxchg` (to see which is causing the hang, then we can compare llvm vs gcc disassembly)?

**Comment by nathanchance** [comment]
Well there are only four call sites of `try_cmpxchg` and it appears the problematic one is `arch_atomic_try_cmpxchg`, which gets used in `atomic_try_cmpxchg`, which appears in a lot of the atomic macros and it explodes from there.

However, I noticed that 4.19 doesn't have a boot issue in CI but 4.20 does. So I bisected v4.19 to v4.20-rc1 and it turns out that reverting 27df89689e257cccb604fdf56c91a75a25aa554a in lieu of the diff I posted above also fixes booting.

**Comment by dileks** [comment]
@nathanchance Thanks for the analysis.

Is this (in)dependent of a llvm-toolchain with asm-goto support?
What SVN/Git versions of llvm and clang did you try?

**Comment by nathanchance** [comment]
I'm using the monorepo and this issue has happened since https://github.com/llvm/llvm-project/commit/90868bb0584f657c2b307309c217dece1f13b0ac (corresponding SVN revision is in the commit message). It can still be observed on tip of tree. I have not included the commit to enable asm-goto in Clang.

**Comment by dileks** [comment]
What/Where is the Z flag in https://github.com/llvm/llvm-project/commit/90868bb0584f657c2b307309c217dece1f13b0ac?

```
[ clang/lib/Basic/Targets/X86.cpp ]

static unsigned matchAsmCCConstraint(const char *&Name) {
  auto RV = llvm::StringSwitch<unsigned>(Name)
                ...
                .Case("@ccz", 4)
```

**Comment by nickdesaulniers** [comment]
Something seems backwards with Clang: https://godbolt.org/z/ExDEAg
The only difference it seems in the emitted assembly is that GCC emits `setc %al` (which is what I would have expected, while Clang emits `setb %al` (what?!).  Try changing the source constraint flag to `"=@ccz"`; GCC emits `sete %al` while Clang emits `setne %al` (literally the opposite).  

`"=@ccz"` lookin' straight up wrong: https://godbolt.org/z/sFybYD

Nathan, what happens in that one case `__X86_CASE_L` if you change it to `CC_SET(nz)`, then `success = !success;` before the break but after the asm?  It looks like with that (from my repro) both compilers should conditionally set the byte based on the correct flag (but it looks like `=@ccz` is picking the wrong flag to check against.  [What's up with that](https://www.youtube.com/watch?v=sqpnRyfz_aY), @niravhdave ? 🎵 🎺

**Comment by niravhdave** [comment]
Oof. That's a super obvious copy-paste error I should have caught.
Appologies for all the legwork to find it.

 Fix landed in rL354588.

**Comment by ramosian-glider** [comment]
This fixed a similar problem in KMSAN tree for me. Thanks, Nirav!
(Hope this'll teach me to look up known bugs before bisecting them myself)

**Comment by nickdesaulniers** [comment]
Thanks @niravhdave!
https://github.com/llvm/llvm-project/commit/dce91c1edbece110bdcbc41095cbd71e9efe2a96
Is my other godbolt case still wrong? `=@ccc`

**Comment by nathanchance** [comment]
I can confirm that dce91c1edbece110bdcbc41095cbd71e9efe2a96 resolves this issue, thanks for the fix @niravhdave!

`Linux version 5.0.0-rc7+ (nathan@archlinux-ryzen) (clang version 9.0.0 (git://github.com/llvm/llvm-project 12a21e4b69d4f156490cc82bee3d4b28368b4840)) #1 SMP Thu Feb 21 10:20:40 MST 2019`

**Comment by niravhdave** [comment]
No. That's fine. setb and setc are aliases.

-Nirav

**Comment by dileks** [comment]
I was able to built and boot into bare metal on Debian/buster AMD64 with a llvm-toolchain-9 with asm-goto support:
```
linux-git: e60b5f79bd75 Merge tag 'powerpc-5.0-6' of git://git.kernel.org/pub/scm/linux/kernel/git/powerpc/linux
llvm-git:  c08de5fe6393 [X86] Fix copy-paste error in @ccz flag.
clang-git: 6a9d9dddc230 [X86] Prevent clang clobber checking for asm flag constraints.
D56571:    diff 187124
```
Applied patches:
```
$ git log --oneline --no-merges origin/HEAD..
ceb8873a6687 scsi: fcoe: make use of fip_mode enum complete
aadf16734696 KVM: x86: asm-goto: Workaround CBL issue #315 and #316
0670525ded48 WIP: asm goto: x86: convert some __always_inline functions to macros
```
Hooray.
```
$ cat /proc/version 
Linux version 5.0.0-rc7-1-amd64-cbl-asmgoto (sedat.dilek@gmail.com@iniza) (clang version 9.0.0 (https://github.com/llvm-mirror/clang.git 6a9d9dddc230e461a95921b306558553c955f010) (https://github.com/llvm-mirror/llvm.git c08de5fe639302cec42bd72d2a30b0ce22797e66)) #1~buster+dileks1 SMP 2019-02-23
```
[config-5.0.0-rc7-1-amd64-cbl-asmgoto.txt](https://github.com/ClangBuiltLinux/linux/files/2897445/config-5.0.0-rc7-1-amd64-cbl-asmgoto.txt)
