### ISSUE TITLE
[llvm-objcopy] broken for x86_64 4.9 and older

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#480]
copypasta from @nathanchance in https://github.com/ClangBuiltLinux/continuous-integration/issues/164:

https://travis-ci.com/ClangBuiltLinux/continuous-integration/jobs/199950119
https://travis-ci.com/ClangBuiltLinux/continuous-integration/jobs/199950119
https://travis-ci.com/ClangBuiltLinux/continuous-integration/jobs/199950121

```
llvm-objcopy-9: error: 'firmware/e100/d101m_ucode.bin.ihex': The file was not recognized as a valid object file
```

Relevant bits of Makefile:

```
fw-shipped-$(CONFIG_E100) += e100/d101m_ucode.bin e100/d101s_ucode.bin \
			     e100/d102e_ucode.bin
...
quiet_cmd_ihex  = IHEX    $@
    cmd_ihex  = $(OBJCOPY) -Iihex -Obinary $< $@
```

This was "resolved" upstream by https://github.com/torvalds/linux/commit/5620a0d1aacd554ebebcff373e31107bb1ef7769, which we obviously can't backport. We could apply a local patch that removes the `fw-shipped` rule in the Makefile or fix `llvm-objcopy` (if it is even broken).

cc @rupprecht

**Comment by rupprecht** [comment]
ihex support is coming in D60270, but I haven't had any time in the past few weeks to review it.

**Comment by nickdesaulniers** [comment]
cool, no rush then; I'll revert the use of llvm-objcopy for our CI for now.  I'd prefer to simply add the support then on the LLVM side, since we're so close.

**Comment by nathanchance** [comment]
[D60270](https://reviews.llvm.org/D60270) appears to work fine, I just applied it locally to test.

It does appear that it was broken up into reading/writing but I can't find the reading half on Phabricator (which we need).

I was able to apply it locally using these two commands:

```
curl -LSs 'https://reviews.llvm.org/D60270?id=193910&download=true' | git apply -3 -p0 --directory=llvm --exclude=llvm/tools/llvm-objcopy/CopyConfig.cpp

curl -LSs 'https://reviews.llvm.org/D60270?download=true' | git apply -3 -p0 --directory=llvm --include=llvm/tools/llvm-objcopy/CopyConfig.cpp
```

**Comment by nickdesaulniers** [comment]
Fixed: https://reviews.llvm.org/rL361949

Maybe time to try llvm-objcopy again.

**Comment by nathanchance** [comment]
It is still broken, even with this patch: https://github.com/ClangBuiltLinux/continuous-integration/issues/183#issuecomment-506861074

I'd be fine with whitelisting 4.4 but that will add some complexity to either driver.sh or our Travis matrix.
