### ISSUE TITLE
drivers/hwmon/pmbus/adm1275.o: warning: objtool: adm1275_probe()+0x744: unreachable instruction

### ISSUE THREAD

**Issue by ms178** [ClangBuiltLinux/linux#621]
With -O3, linux-next-next-20190726 and clang version 10.0.0 (366783), there is an objtool warning observed in:

drivers/hwmon/pmbus/adm1275.o: warning: objtool: adm1275_probe()+0x744: unreachable instruction

It should be reproducible while using the attached config plus Makefile and /arch/x86/Makefile settings.

[buildlog_Westmere_2.txt](https://github.com/ClangBuiltLinux/linux/files/3438031/buildlog_Westmere_2.txt)

[config_Westmere_2.txt](https://github.com/ClangBuiltLinux/linux/files/3438034/config_Westmere_2.txt)

[Makefile_Westmere_2.txt](https://github.com/ClangBuiltLinux/linux/files/3438037/Makefile_Westmere_2.txt)

[arch_x86_Makefile.txt](https://github.com/ClangBuiltLinux/linux/files/3438039/arch_x86_Makefile.txt)

_Originally posted by @ms178 in https://github.com/ClangBuiltLinux/linux/issues/548#issuecomment-515672728_

**Comment by ms178** [comment]
Testing with -O2, linux-next-next-20190730 and clang version 10.0.0 (366783) also confirmed this issue.

[buildlog_o2.txt](https://github.com/ClangBuiltLinux/linux/files/3445552/buildlog_o2.txt)

It now errors out at the end with:

WARNING: "phys_base" [vmlinux] is the static EXPORT_SYMBOL
WARNING: "ahci_em_messages" [vmlinux] is the static EXPORT_SYMBOL_GPL
WARNING: "ftrace_set_clr_event" [vmlinux] is the static EXPORT_SYMBOL_GPL
WARNING: "empty_zero_page" [vmlinux] is the static EXPORT_SYMBOL
WARNING: "hypercall_page" [vmlinux] is the static EXPORT_SYMBOL_GPL
MODINFO modules.builtin.modinfo
ld: drivers/gpio/gpiolib-devres.o: in function devm_gpiod_get_from_of_node': (.text+0x172): undefined reference to gpiod_get_from_of_node'

**Comment by nathanchance** [comment]
Still reproducible with ToT LLVM and kernel with the provided `.config`.

**Comment by nathanchance** [comment]
`creduce` spits out:

```
a, d, e;
struct {
  short b
} c[];
f() {
  switch (a & (1 << 5 | 1)) {
  case 0:;
    break;
  case 1 << 5:
    e = 5;
    break;
  case 1:
  case 1 << 5 | 1:
    e = 7;
  }
  d = c[e].b;
}
```

```
$ ~/src/linux/out/x86_64/tools/objtool/objtool orc generate --module --no-fp adm1275.o
adm1275.o: warning: objtool: f()+0x2f: unreachable instruction

$ llvm-objdump -D --section=.text adm1275.o

adm1275.o:      file format elf64-x86-64


Disassembly of section .text:

0000000000000000 <f>:
       0: e8 00 00 00 00                callq   0x5 <f+0x5>
       5: 8b 05 00 00 00 00             movl    (%rip), %eax  # b <f+0xb>
       b: 83 e0 21                      andl    $33, %eax
       e: ff 24 c5 00 00 00 00          jmpq    *(,%rax,8)
      15: c7 05 00 00 00 00 07 00 00 00 movl    $7, (%rip)  # 1f <f+0x1f>
      1f: b8 07 00 00 00                movl    $7, %eax
      24: eb 18                         jmp     0x3e <f+0x3e>
      26: 48 63 05 00 00 00 00          movslq  (%rip), %rax  # 2d <f+0x2d>
      2d: eb 0f                         jmp     0x3e <f+0x3e>
      2f: c7 05 00 00 00 00 05 00 00 00 movl    $5, (%rip)  # 39 <f+0x39>
      39: b8 05 00 00 00                movl    $5, %eax
      3e: 0f bf 84 00 00 00 00 00       movswl  (%rax,%rax), %eax
      46: 89 05 00 00 00 00             movl    %eax, (%rip)  # 4c <f+0x4c>
      4c: c3                            retq
```

cc @jpoimboe

**Comment by jpoimboe** [comment]
This one looks familiar -- the switch statement jump table has dead code entries which point to the nop past the end of the function.  I think there was another issue open for this which was recently closed today because it's fixed in clang 11? (sorry I don't have the issue #).

**Comment by nathanchance** [comment]
#611 was the issue. Odd since this was reproduced with ToT LLVM :/

**Comment by nickdesaulniers** [comment]
Still an issue, reported upstream: https://llvm.org/pr50080,
